//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaSet()
        {
            this.ItemMenuSet = new HashSet<ItemMenuSet>();
        }
    
        public int IdCategoria { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMenuSet> ItemMenuSet { get; set; }

        public override string ToString()
        {
            if(this.Ativo)
            {
                return "#" + this.IdCategoria + " - " + this.Nome + " (Ativo)";
            } else
            {
                return "#" + this.IdCategoria + " - " + this.Nome + " (Desativado)";
            }
        }
    }
}
