//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPagamentoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetodoPagamentoSet()
        {
            this.PagamentoSet = new HashSet<PagamentoSet>();
        }
    
        public int IdMetodo { get; set; }
        public string MetododePagamento { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoSet> PagamentoSet { get; set; }

        public override string ToString()
        {
            if (this.Ativo)
            {
                return "#" + this.IdMetodo + " - " + this.MetododePagamento + " (Ativo)";
            }
            else
            {
                return "#" + this.IdMetodo + " - " + this.MetododePagamento + " (Desativado)";
            }
        }
    }
}
