//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int IdPessoa { get; set; }
        public string Nome { get; set; }
        public int Telemovel { get; set; }
        public int Morada_IdMorada { get; set; }
    
        public virtual MoradaSet MoradaSet { get; set; }
        public virtual Pessoa_Cliente Pessoa_Cliente { get; set; }
        public virtual Pessoa_Trabalhador Pessoa_Trabalhador { get; set; }

        public override string ToString()
        {
            return this.Nome;
        }
    }
}
