//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa_Cliente()
        {
            this.PedidoSet = new HashSet<PedidoSet>();
        }
    
        public double TotalGasto { get; set; }
        public int NumContribuinte { get; set; }
        public int IdPessoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoSet> PedidoSet { get; set; }
        public virtual Pessoa Pessoa { get; set; }

        public override string ToString()
        {
            return "#" + this.IdPessoa + " - " + this.Pessoa.Nome + " (" + this.NumContribuinte + ")";
        }
}
}
