//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteAPPContainer : DbContext
    {
        public RestauranteAPPContainer()
            : base("name=RestauranteAPPContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Restaurante> Restaurante { get; set; }
        public virtual DbSet<Morada> MoradaSet { get; set; }
        public virtual DbSet<ItemMenu> ItemMenuSet { get; set; }
        public virtual DbSet<Pedido> PedidoSet { get; set; }
        public virtual DbSet<EstadoPedido> EstadoPedidoSet { get; set; }
        public virtual DbSet<Pagamento> PagamentoSet { get; set; }
        public virtual DbSet<MetodoPagamento> MetodoPagamentoSet { get; set; }
        public virtual DbSet<Categoria> CategoriaSet { get; set; }
    }
}
