//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_APP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteAPPContainer : DbContext
    {
        public RestauranteAPPContainer()
            : base("name=RestauranteAPPContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaSet> CategoriaSet { get; set; }
        public virtual DbSet<EstadoPedidoSet> EstadoPedidoSet { get; set; }
        public virtual DbSet<ItemMenuSet> ItemMenuSet { get; set; }
        public virtual DbSet<MetodoPagamentoSet> MetodoPagamentoSet { get; set; }
        public virtual DbSet<MoradaSet> MoradaSet { get; set; }
        public virtual DbSet<PagamentoSet> PagamentoSet { get; set; }
        public virtual DbSet<PedidoSet> PedidoSet { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Pessoa_Cliente> Pessoa_Cliente { get; set; }
        public virtual DbSet<Pessoa_Trabalhador> Pessoa_Trabalhador { get; set; }
        public virtual DbSet<Restaurante> Restaurante { get; set; }
    }
}
